version: "3"
services:
  r:
    # image: atusy/atusyverse:dev
    build:
      context: "."
      dockerfile: Dockerfile
    ports:
      - "8787"
    environment:
      - USER=rstudio
      - PASSWORD=password
      - ROOT=true
      - VIRTUAL_HOST=atusyverse.localhost
    network_mode: "bridge"
