version: "3"
services:
  r:
    # image: atusy/atusyverse:dev
    build:
      context: "."
      dockerfile: Dockerfile-minimal
    restart: always
    ports:
      - "8789:8787"
    environment:
      - USER=rstudio
      - PASSWORD=password
      - ROOT=true
      - VIRTUAL_HOST=atusyverse.local
    network_mode: "bridge"
